require "user.autopairs"
require "user.bufferline"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.indentline"
require "user.keymaps"
require "user.lsp"
require "user.nvim-tree"
require "user.options"
require "user.plugins"
require "user.telescope"
require "user.treesitter"
require "user.lualine"

